### ISSUE TITLE
Consider switching from Travis to GitHub actions

### ISSUE THREAD

**Issue by peter279k** [sebastianfeldmann/crontab#3]
As title, it seems that some of packages (such as [git](https://github.com/sebastianfeldmann/git
) package) has been switched from Travis CI build to GitHub actions.

I think this package should can consider switching from Travis to GitHub actions, too.

If this issue has been accepted, I would be happy to work on this :).

**Comment by sebastianfeldmann** [comment]
Sounds great :)

**Comment by sebastianfeldmann** [comment]
Done ;)
